# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:03:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ExudeBean(BaseModel):
    data: Optional[str] = None
    links: Optional[List[str]] = None


class ExudeResponseBean(BaseModel):
    data: Optional[str] = None


class ExudeTypeFilePostRequest(BaseModel):
    file: Optional[bytes] = None
